<Project Sdk="OpenStrata.Build.NoTargets">

  <PropertyGroup>
    <TargetFramework>net462</TargetFramework>

    <!--WebSiteId is unique to portal config and common to all environments-->
    <WebSiteId>WebSiteId.1</WebSiteId>
    <WebSiteFolder>WebSiteFolder.1</WebSiteFolder>

  </PropertyGroup>

  <ItemGroup>

    <PackageReference Include="OpenStrata.MSBuild.PowerPages" Version="ostrataVersion.1">
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>

		<PowerPagesPaths Include="$(WebSiteFolder)" />
		<None Include="$(WebSiteFolder)\**\*.*" />

  </ItemGroup>

</Project>
