<Project Sdk="OpenStrata.Build.NoTargets">

  <PropertyGroup>
    <TargetFramework>net462</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <!--<PackageReference Include="OpenStrata.MSBuild.AppSource" Version="ostrataversion">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>-->
    <PackageReference Include="OpenStrata.MSBuild.PowerPages" Version="ostrataversion">
      <PrivateAssets>all</PrivateAssets>
      <!--<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>-->
    </PackageReference>
  </ItemGroup>

</Project>
