<Project Sdk="OpenStrata.Build.NoTargets">

  <PropertyGroup>
    <TargetFramework>net462</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="OpenStrata.MSBuild.PCF" Version="ostrataVersion">
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>

</Project>
