<Project Sdk="OpenStrata.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
	  <AssemblyName>OstrataTemplate.1.Deployment</AssemblyName>
	  <RootNamespace>OstrataTemplate._1.Deployment</RootNamespace>	    
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="OpenStrata.MSBuild.Deployment" Version="ostrataVersion.1">
		     <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>

</Project>
