<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ItemGroup>
    <ProjectReference Include="Solution\OstrataTemplate.1.Solution.cdsproj" Condition="Exists('Solution\OstrataTemplate.1.Solution.cdsproj')">
      <AdditionalProperties>Configuration=$(Configuration); Platform=AnyCPU</AdditionalProperties>
      <Configuration>$(Configuration)</Configuration>
      <Platform>AnyCPU</Platform>
    </ProjectReference>
    <ProjectReference Include="PCF\**\*.pcfproj">
      <AdditionalProperties>Configuration=$(Configuration); Platform=AnyCPU</AdditionalProperties>
      <Configuration>$(Configuration)</Configuration>
      <Platform>AnyCPU</Platform>
    </ProjectReference>    
  </ItemGroup>
</Project>