<Project Sdk="OpenStrata.Build.NoTargets">

  <PropertyGroup>
    <TargetFramework>net462</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Openstrata.MSBuild.ConfigData" Version="ostrataVersion">
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
	  <ProjectReference Condition="Exists('..\Solution\OstrataTemplate.1.Solution.csproj')" Include="..\Solution\OstrataTemplate.1.Solution.csproj" />
  </ItemGroup>

</Project>
