<Project Sdk="OpenStrata.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>

	  <AssemblyName>OstrataTemplate.1.Package</AssemblyName>
	  <RootNamespace>OstrataTemplate._1.Package</RootNamespace>
	  
	  
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="OpenStrata.MSBuild.Package" Version="0.8.*">
      <PrivateAssets>all</PrivateAssets>
      <!--<IncludeAssets>compile;runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>-->
    </PackageReference>
  </ItemGroup>


	<PropertyGroup Label="Set Package Properties">
		<!--<ImportPackageShortName ></ImportPackageShortName>-->
		<!--<ImportPackageLongName ></ImportPackageLongName>-->
		<!--<ImportPackageDescription ></ImportPackageDescription>-->
		<!--<ImportPackageDataFolder ></ImportPackageDataFolder>-->
	</PropertyGroup>

	<PropertyGroup Label="Set Appsource Package properties">
		<!--<CreateAppSourcePackage></CreateAppSourcePackage>-->
		<!--<AppSourceSupportedCountries></AppSourceSupportedCountries>-->
		<!--<AppSourceLearnMoreLink></AppSourceLearnMoreLink>-->
		<!--<AppSourceProviderName></AppSourceProviderName>-->
		<!--<AppSourceStartDate></AppSourceStartDate>-->
		<!--<AppSourceEndDate></AppSourceEndDate>-->
	</PropertyGroup>	

  <ItemGroup>
	  <ProjectReference Condition="Exists('..\ConfigData\OstrataTemplate.1.ConfigData.csproj')" Include="..\ConfigData\OstrataTemplate.1.ConfigData.csproj"  />
	  <ProjectReference Condition="Exists('..\Deployment\OstrataTemplate.1.Deployment.csproj')" Include="..\Deployment\OstrataTemplate.1.Deployment.csproj" />
	  <ProjectReference Condition="Exists('..\Publisher\OstrataTemplate.1.Publisher.csproj')" Include="..\Publisher\OstrataTemplate.1.Publisher.csproj" />
	  <ProjectReference Condition="Exists('..\Solution\OstrataTemplate.1.Solution.csproj')" Include="..\Solution\OstrataTemplate.1.Solution.csproj" />
	  <ProjectReference Condition="Exists('..\PowerPages\OstrataTemplate.1.PowerPages.csproj')" Include="..\PowerPages\OstrataTemplate.1.PowerPages.csproj" />
	  <ProjectReference Condition="Exists('..\DocTemplates\OstrataTemplate.1.DocumentTemplates.csproj')" Include="..\DocTemplates\OstrataTemplate.1.DocumentTemplates.csproj" />
  </ItemGroup>

</Project>
