<Project Sdk="OpenStrata.Build.NoTargets">

	<PropertyGroup>
		<TargetFramework>net472</TargetFramework>

		<DataverseSolutionName>OstrataTemplate.1</DataverseSolutionName>
		<DataversePublisherUniqueName>publishername.1</DataversePublisherUniqueName>
		<DataversePublisherPrefix>publisherPrefix.1</DataversePublisherPrefix>


		<!--<RemoveActiveDependencies>true</RemoveActiveDependencies>	-->		

		<!-- <IncludeAutoNumbering >true</IncludeAutoNumbering> -->
		<!-- <IncludeCalendar >true</IncludeCalendar> -->
		<!-- <IncludeCustomization >true</IncludeCustomization> -->
		<!-- <IncludeEmailTracking >true</IncludeEmailTracking> -->
		<!-- <IncludeAutoNumbering >true</IncludeAutoNumbering> -->
		<!-- <IncludeGeneral >true</IncludeGeneral> -->
		<!-- <IncludeISVConfig >true</IncludeISVConfig> -->
		<!-- <IncludeMarketing >true</IncludeMarketing> -->
		<!-- <IncludeOutlookSynchronization >true</IncludeOutlookSynchronization> -->
		<!-- <IncludeRelationshipRoles >true</IncludeRelationshipRoles> -->
		<!-- <IncludeSales >true</IncludeSales> -->


	
	</PropertyGroup>

  <ItemGroup>
    <PackageReference Include="OpenStrata.MSBuild.Solution" Version="ostrataVersion.1">
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>

	  <!--Modify the publisher reference as appropriate -->

	  <!--<PackageReference Include="" Version="1.*">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	  </PackageReference>-->
  
  </ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\PCF\**\*.pcfproj" Exclude="@(PcfProjExcludes)" />
		<PluginReference Include="..\Plugin\OstrataTemplate.1.Plugin.csproj" Condition="Exists('..\Plugin\OstrataTemplate.1.Plugin.csproj')"/>
	</ItemGroup>

	<ItemGroup Label="SolutionXmlDependencyCleanup">
		<!--<AttributeDependenciesToRemove Include="[AttributeID]" />-->
		<!--<SolutionDependenciesToRemove Include="[SolutionID]" />-->
		<!--<RequiredTypeDependenciesToRemove Include="[ComponentType]" />-->
		<!--<DependentTypeDependenciesToRemove Include="[ComponentType]" />-->
		<!--<SolutionDependencyMinVersion Include="[SolutionID]" MinVersion="[MinVersion]"  />-->						   
	</ItemGroup>

</Project>
